### ISSUE TITLE
efi mapper

### ISSUE THREAD

**Issue by stogies** [btbd/hwid#20]
is it possible to use the an efi mapper to map this to driver and run at startup?

**Comment by btbd** [comment]
@stogies It's possible but it may not function properly as it depends on when this driver is actually loaded and how you are hooking the other drivers.

For example, let's say we are replacing the mapper in [this](https://github.com/btbd/umap) with this  repository's driver. If we used this repository's master branch, which does a MajorFunction pointer swap, then it wouldn't work as our DriverEntry will be called before all the boot-time DriverEntries, so no driver objects exist for us to hook.

However, if you were to use the hook branch that places inline hooks, then it *would* work because the drivers' images exist in memory and are in the loaded module list.
